App/App/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using App.Models;
using HttpRequests;
using DataTransferObjects;
using Records.Models;
using Communication.Models;


namespace App.Controllers
{
    public class AppController : Controller
    {
        public static string UsersManagerUrl = "http://localhost:55577";
        public static string AppUrl = "http://localhost:54055/app";
        public static string RecordsUrl = "http://localhost:54090/";
        public static string CommunicationUrl = "http://localhost:54101/";

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Prices()
        {         
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegisterUser(string email, string passwordHash, string name, string lastName,
            string middleName, string mobilePhone, DateTime birthDate, string hostName)
        {
            var user = new UserFullInfo(email, passwordHash, name, lastName, middleName, mobilePhone, birthDate);
            var response = PostRequest.ExecuteAsync<UserBasicInfo>(UsersManagerUrl + "/api/Users/RegisterUser", user).Result;

            if (response.IsSuccess)
                return Ok(new { uri = hostName + $"/App/RegistrationSuccess?name={name}&lastName={lastName}&middleName={middleName}" });
            else
                return Ok(new { uri = hostName + "/App/RegistrationFail" });
        }

        public IActionResult RegistrationSuccess(string name, string lastName, string middleName)
        {
            ViewData["UserFio"] = lastName + " " + name + " " + middleName;
            ViewData["AppUrl"] = AppUrl;
            return View();
        }

        public IActionResult RegistrationFail()
        {
            ViewData["RegUrl"] = AppUrl + "/Registration";
            return View();
        }

        [HttpPost]
        public IActionResult AuthorizeUser(string email, string passwordHash, string hostName)
        {
            var user = new UserAuthInfo(email, passwordHash);
            var response = PostRequest.ExecuteAsync<UserAuthResponse>(UsersManagerUrl + "/api/Users/VerifyUser", user).Result;
            
            if (response.IsSuccess)
            {
                TempData["LayoutFio"] = response.Data.UserBasicInfo.LastName + " " + response.Data.UserBasicInfo.Name;
                TempData["TokenBody"] = response.Data.TokenBody;

                return Ok(new { uri = hostName });
            }
            else
                return Ok(new { uri = hostName + "/App/Authorize?fail=1" });
        }

        public IActionResult Authorize(int fail = 0)
        {
            ViewData["FailFlg"] = fail;
            return View();
        }

        public RedirectResult Exit()
        {
            TempData.Remove("LayoutFio");
            TempData.Remove("TokenBody");
            
            return Redirect(AppUrl);
        }

        [HttpGet]
        public IActionResult Doctors()
        {
            var response = GetRequest.ExecuteAsync<List<Doctor>>(RecordsUrl + "/api/Records/Doctors").Result;

            if (response.IsSuccess)
            {
                return View(response.Data);
            }
            else
            {
                ViewData["ErrorTextMessage"] = "Невозможно получить информацию о докторах.";
                return View("UserErrorPage");
            }
            // string speciality = Converters.SpecialityToStringConverter.Convert(doctor.Speciality);
            //string day = Converters.DayToStringConverter.Convert(doctor.Schedule);
        }

        public IActionResult CalendarReservation(string name, string lastName, string middleName)
        {
            if (TempData.ContainsKey("TokenBody"))
            {
                var responseCheckToken = PostRequest.ExecuteAsync<UserBasicInfo>(UsersManagerUrl + "/api/Users/CheckToken", TempData.Peek("TokenBody").ToString()).Result;

                if (responseCheckToken.IsSuccess)
                {
                    ViewData["UserFio"] = responseCheckToken.Data.Name + " " + responseCheckToken.Data.LastName + " " + responseCheckToken.Data.MiddleName;
                    var response = GetRequest.ExecuteAsync<Doctor>(RecordsUrl + $"/api/Records/Doctors/{name}/{lastName}/{middleName}").Result;
                    if (response.IsSuccess)
                    {
                        return View(response.Data);
                    }
                    else
                    {
                        ViewData["ErrorTextMessage"] = "Невозможно получить информацию о расписании доктора.";
                        return View("UserErrorPage");
                    }
                }
                else
                {
                    TempData.Remove("TokenBody");
                    TempData.Remove("LayoutFio");
                    return RedirectToAction("Authorize");
                }
            }
            else
            {
                return RedirectToAction("Authorize");
            } 
        }

        public IActionResult DoctorSchedule(string currentDate, string doctorId)
        {
            var response = GetRequest.ExecuteAsync<List<(DateTime,bool)>>(RecordsUrl + $"/api/Records/Doctors/{currentDate}/{doctorId}").Result;

            if (response.IsSuccess)
            {      
                ViewData["doctorId"] = doctorId;
                return View(response.Data);
            }
            else
            {
                ViewData["ErrorTextMessage"] = "Невозможно получить информацию о рабочем графике и занятости доктора.";
                return View("UserErrorPage");
            }
            // string speciality = Converters.SpecialityToStringConverter.Convert(doctor.Speciality);
            //string day = Converters.DayToStringConverter.Convert(doctor.Schedule);
        }
        
        public IActionResult AddUserReservation(string time, string doctorId)
        {
            if (!TempData.ContainsKey("TokenBody"))
            {
                ViewData["ErrorTextMessage"] = "Невозможно получить информацию о токене";
                return View("UserErrorPage");
            }

            var responseCheckToken = PostRequest.ExecuteAsync<UserBasicInfo>(UsersManagerUrl + "/api/Users/CheckToken", TempData.Peek("TokenBody").ToString()).Result;
            if (responseCheckToken.IsSuccess)
            {
                ReservationInfo reservationInfo = new ReservationInfo(responseCheckToken.Data.Id, Guid.Parse(doctorId), DateTime.Parse(time));
                var response = PostRequest.ExecuteAsync<(Reservation,bool)>(RecordsUrl + "/api/Records/AddReservation", reservationInfo).Result;
                if (!response.IsSuccess)
                {
                    ViewData["ErrorTextMessage"] = "Ошибка сервера. Попробуйте позже.";
                    return View("UserErrorPage");
                }

                if (response.Data.Item2 == false)
                {
                    if (response.Data.Item1 != null)
                        return View(response.Data.Item1);
                    else
                    {
                        ViewData["ErrorTextMessage"] = "Невозможно добавить информацию о записе ко врачу. У вас уже есть активная запись. Обратитесь к администратору.";
                        return View("UserErrorPage");
                    }
                }
                else
                {
                    ViewData["ErrorTextMessage"] = "Невозможно добавить информацию о записе ко врачу. Ошибка сервера. Доктор не найден";
                    return View("UserErrorPage");
                }
            }
            else
            {
                TempData.Remove("TokenBody");
                TempData.Remove("LayoutFio");
                return RedirectToAction("Authorize");
            }
        }

        public IActionResult UserReservation()
        {
            if (!TempData.ContainsKey("TokenBody"))
            {
                ViewData["ErrorTextMessage"] = "Невозможно получить информацию о токене";
                return View("UserErrorPage");
            }

            var responseCheckToken = PostRequest.ExecuteAsync<UserBasicInfo>(UsersManagerUrl + "/api/Users/CheckToken", TempData.Peek("TokenBody").ToString()).Result;
            if (responseCheckToken.IsSuccess)
            {
                if (responseCheckToken.Data.IsAdmin)
                {
                    return RedirectToAction("AdminReservationPage");
                }

                var response = PostRequest.ExecuteAsync<(Reservation, bool)>(RecordsUrl + "/api/Records/UserReservation", responseCheckToken.Data.Id).Result;
                if (!response.IsSuccess)
                {
                    ViewData["ErrorTextMessage"] = "Ошибка сервера. Попробуйте позже.";
                    return View("UserErrorPage");
                }

                if (response.Data.Item2 == false)
                {
                    if (response.Data.Item1 != null)
                        return View(response.Data.Item1);
                    else
                    {
                        ViewData["ErrorTextMessage"] = "Ошибка сервера. Попробуйте позже.";
                        return View("UserErrorPage");
                    }
                }
                else
                {
                    ViewData["ErrorTextMessage"] = "Невозможно просмотреть информацию о записе ко врачу. Ошибка сервера. Актуальные записи пользователя не найдены.";
                    return View("UserErrorPage");
                }
            }
            else
            {
                TempData.Remove("TokenBody");
                TempData.Remove("LayoutFio");

App/App/Views/Shared/_Layout.cshtml
@{
    string fio = (TempData.ContainsKey("LayoutFio")) ? (string)TempData.Peek("LayoutFio") : "Гость";
    string actionButton = (TempData.ContainsKey("LayoutFio")) ? "UserReservation" : "Authorize";
    string nameButton = (TempData.ContainsKey("LayoutFio")) ? "Мои записи" : "Войти" ;

    string actionMessageButton = (TempData.ContainsKey("LayoutFio")) ? "Messages" : "Registration";
    string nameMessageButton = (TempData.ContainsKey("LayoutFio")) ? "Мои сообщения" : "Зарегестрироваться";

    string loginButtonsVisibility = (TempData.ContainsKey("LayoutFio")) ? "hidden" : "visible";
    string exitButtonVisibility = (TempData.ContainsKey("LayoutFio")) ? "visible" : "hidden";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ДентАурум</title>
    <style>
        .login-buttons {
        visibility: @loginButtonsVisibility;
    }
        .exit-button{
        visibility: @exitButtonVisibility;
    }
    </style>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/js/sha256.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
    <link href="/css/lightbox.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="/images/dentaurum_favicon.ico" type="image/x-icon">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="App" asp-action="Index">Главная</a></li>
                    <li><a asp-area="" asp-controller="App" asp-action="Doctors">Врачи</a></li>
                    <li><a asp-area="" asp-controller="App" asp-action="Prices">Стоимость услуг</a></li>
                    <li><a asp-area="" asp-controller="App" asp-action="Contact">Контакты</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a style="color: white">Вы вошли как <b>@fio</b></a></li>
                    <li><a style="color: white" asp-area="" asp-controller="App" asp-action=@actionButton>@nameButton</a></li>
                    <li><a style="color: white" asp-area="" asp-controller="App" asp-action=@actionMessageButton>@nameMessageButton</a></li>       
                    <li><a class="exit-button" style="color: white" asp-area="" asp-controller="App" asp-action="Exit">Выйти</a></li>  
                </ul>
            </div>
        </div>
    </nav>
    <header class="container">
        <div class="col-md-12 row">
            <div class="col-md-4 img-logo">
                <img src="~/images/lala.png" width="770" height="220">
            </div>
            <div class="top-info">
                <h3>
                    <img src="~/images/phone.png" alt="phone" align="left" width="45" height="45">
                    <div class="phone"><b>&nbsp +7(495) 123-55-68</b></div>
                    <br>
                    <img src="~/images/email.png" alt="email" align="left" width="45" height="45">
                    <div class="email"><b>&nbsp bikus@inbox.ru</b></div>
                </h3>
            </div>
        </div>
    </header>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <div class="footer-info">
                <div class="row">
                    <div class="col-md-9">
                        <p> Стоматологическая клиника </p>
                        <p>"ДентАурум" </p>
                        <p>&copy; Все права защищены, 2016</p>
                    </div>
                    <div class="col-md-3 ">
                        <p>+7(495) 123-55-68</p>
                        <p>Нагатинская набережная, 10к3</p>
                        <p>2016bikus@inbox.ru</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>